const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),vm=require('vm');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.join(__dirname,'..');
for(const file of fs.readdirSync(path.join(root,'lessons')).filter(x=>x.endsWith('.js')))new vm.Script(fs.readFileSync(path.join(root,'lessons',file),'utf8'),{filename:file});
new vm.Script(fs.readFileSync(path.join(root,'sw.js'),'utf8'));
for(const [,code] of fs.readFileSync(path.join(root,'index.html'),'utf8').matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(code);
(async()=>{const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0])==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>typeof C2==='object'&&Object.keys(C2).length===36);
 const ids=await page.evaluate(()=>modules.map(m=>m.id));assert.equal(ids.length,36);assert.equal(await page.locator('#subjects .subject').count(),8);
 await page.evaluate(()=>{state.testSentinel='preserve';state.variant['u-sound']=5;state.done['u-sound']=['5'];state.last='u-sound';persist()});await page.getByRole('button',{name:'Продовжити',exact:true}).click();assert.equal(await page.locator('[data-topic]').getAttribute('data-topic'),'u-sound');assert((await page.locator('#c2-done5').innerText()).includes('✓'));
 async function answer(key,value){await page.locator('#'+key).fill(String(value));await page.locator('#'+key).locator('..').locator('button').click()}
 async function fb(key,ok){assert((await page.locator('#'+key+'-fb').innerText()).startsWith(ok?'✓':'Спробуй ще'),key+' '+await page.locator('#'+key+'-fb').innerText())}
 let practice=0,quiz=0,activities=0,missions=0;
 for(const id of ids){await page.locator('#c2-topic').selectOption(id);const data=await page.evaluate(id=>{const m=modules.find(x=>x.id===id),t=C2[id];return {a:t.activity,bank:B[m.kind],quiz:t.quiz,mission:t.mission.ans}},id);
  const a=data.a;if(a.type==='range'){await answer('c2-model','');await fb('c2-model',false);for(const c of a.controls){for(const v of [c.min,c.max]){await page.locator('#c2-'+c.name).fill(String(v));assert(!(await page.locator('#c2-picture').innerHTML()).match(/NaN|Infinity|undefined/),id);const ans=await page.evaluate(()=>C2[state.last].activity.check.answer(c2Values(C2[state.last])));await answer('c2-model',ans);await fb('c2-model',true)}}}
  else if(a.type==='choose'){for(const q of a.items){await page.locator('[data-c2-pick="'+((q.a+1)%q.options.length)+'"]').click();await fb('c2-activity',false);await page.locator('[data-c2-pick="'+q.a+'"]').click();await fb('c2-activity',true)}}
  else if(a.type==='order'){await page.locator('[data-c2-order]').click();await fb('c2-activity',false);await page.locator('[data-c2-token="'+a.answer[0]+'"]').click();await page.locator('[data-c2-undo]').click();for(const i of a.answer)await page.locator('[data-c2-token="'+i+'"]').click();await page.locator('[data-c2-order]').click();await fb('c2-activity',true);if(id==='u-sent')assert.equal(await page.locator('#c2-built').innerText(),'Діти читають книжку.')}
  else if(a.type==='paint'){await page.locator('[data-c2-created]').click();await fb('c2-activity',false);await page.locator('[data-c2-color]').nth(1).click();await page.locator('[data-c2-paint="0"]').click();await page.locator('[data-c2-created]').click();await fb('c2-activity',true)}activities++;
  await answer('c2-p0','');await fb('c2-p0',false);for(const [i,q]of data.bank.entries()){await answer('c2-p'+i,'invalid wrong value');await fb('c2-p'+i,false);await answer('c2-p'+i,q[0]);await fb('c2-p'+i,true);practice++}const count=await page.evaluate(()=>state.done[state.last].length);await answer('c2-p0',data.bank[0][0]);assert.equal(await page.evaluate(()=>state.done[state.last].length),count);
  for(const [i,q]of data.quiz.entries()){await page.locator('[data-c2-quiz="'+i+'"][data-a="'+((q.a+1)%q.options.length)+'"]').click();await fb('c2-q'+i,false);await page.locator('[data-c2-quiz="'+i+'"][data-a="'+q.a+'"]').click();await fb('c2-q'+i,true);quiz++}
  await answer('c2-mission','invalid wrong value');await fb('c2-mission',false);await answer('c2-mission',data.mission);await fb('c2-mission',true);missions++;
  const r=await page.evaluate(()=>c2Rec(state.last));assert(r.activity&&r.mission&&Object.keys(r.quiz).length===3,id+' results');
  console.log(id+' passed');
 }
 await page.locator('#c2-topic').selectOption('u-spell');await answer('c2-p4','київ');await fb('c2-p4',false);await answer('c2-mission','київ');await fb('c2-mission',false);await answer('c2-p3',"м'яч");await fb('c2-p3',true);
 await page.locator('#c2-topic').selectOption('u-sound');assert.equal(await page.evaluate(()=>B.sound[5][0]),4);await answer('c2-p5',3);await fb('c2-p5',false);await answer('c2-p5',4);await fb('c2-p5',true);
 await page.locator('#c2-topic').selectOption('m-add');await page.locator('#c2-a').fill('28');await page.locator('#c2-b').fill('19');await answer('c2-model',47);await fb('c2-model',true);
 for(const width of [360,390,768,1280]){await page.setViewportSize({width,height:900});for(const id of ['m-add','w-map','r-read','a-rhythm','u-sent','a-color']){await page.evaluate(id=>openLesson(id),id);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),id+' overflow '+width)}await page.screenshot({path:path.join(process.env.OUTPUT_DIR||require('os').tmpdir(),'class2-'+width+'.png')})}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>home());for(const s of await page.evaluate(()=>Object.keys(names))){await page.locator('#subjects .subject').filter({has:page.locator('button[onclick="openFirst(\''+s+'\')"]')}).locator('button').click();assert.equal(await page.evaluate(()=>modules.find(x=>x.id===state.last).s),s);await page.getByRole('button',{name:'Головна',exact:true}).click()}
 await page.getByRole('button',{name:'План на сьогодні',exact:true}).click();await page.locator('#todayContent button').first().click();assert(await page.locator('[data-topic]').isVisible());await page.getByRole('button',{name:'Батькам',exact:true}).click();assert(await page.locator('#pa').innerText());await page.getByRole('button',{name:'Головна',exact:true}).click();await page.getByRole('button',{name:'Продовжити',exact:true}).click();
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;await caches.open('stem7-pwa-v23');await caches.open('unrelated-cache');await caches.open('class2-v7');for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister()});await page.reload();await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(async()=>!(await caches.keys()).includes('class2-v7'));const cachesFound=await page.evaluate(()=>caches.keys());assert(cachesFound.includes('stem7-pwa-v23')&&cachesFound.includes('unrelated-cache')&&cachesFound.includes('class2-v8'));
 await context.setOffline(true);await page.reload();await page.getByRole('button',{name:'Продовжити',exact:true}).click();for(const id of ids)await page.locator('#c2-topic').selectOption(id);assert.equal(await page.evaluate(()=>state.testSentinel),'preserve');assert.equal(await page.evaluate(()=>state.variant['u-sound']),5);assert.deepEqual(await page.evaluate(()=>[KEY,BACK]),['learn2_v1','learn2_v1_backup']);await page.locator('#c2-topic').selectOption('a-color');assert.equal(await page.evaluate(()=>c2Rec('a-color').tiles[0]),'#638ada');assert.deepEqual(errors,[]);
 console.log(JSON.stringify({practice,quiz,activities,missions,mobile:[360,390,768,1280],offline:true,progressPreserved:true,cachesFound,errors}));
 }finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
