/* Age-appropriate interaction primitives; the learning content is authored per topic. */
const C2=Object.create(null);let c2Session={step:0,built:[],color:'#ed775f'};
function c2Topic(id,t){const rotate=(q,i)=>{const n=(id.length+i)%q.options.length;if(n){q.options=q.options.slice(n).concat(q.options.slice(0,n));q.a=(q.a-n+q.options.length)%q.options.length}};t.quiz.forEach(rotate);if(t.activity.type==='choose')t.activity.items.forEach(rotate);C2[id]=t}
function c2Esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function c2SVG(s,label='Навчальна модель'){return `<svg viewBox="0 0 360 240" role="img" aria-label="${c2Esc(label)}">${s}</svg>`}
function c2Text(x,y,s){return `<text x="${x}" y="${y}" text-anchor="middle" font-size="18" fill="#172033">${c2Esc(s)}</text>`}
function c2Box(x,y,w,h,s,color='#e3eaff'){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="7" fill="${color}" stroke="#4b63d3"/>`+c2Text(x+w/2,y+h/2+6,s)}
function c2Range(name,label,min,max,value,step=1){return {name,label,min,max,value,step}}
function c2Q(q,options,a,why){return {q,options,a,why}}
function c2Item(label,options,a,why){return {label,options,a,why}}
function c2Order(tokens,answer,hint){return {type:'order',tokens,answer,hint}}
function c2Choose(...items){return {type:'choose',items}}
function c2Mission(text,q,ans,hint,why){return {text,q,ans,hint,why}}
function c2Rec(id){state.journey=state.journey||{};return state.journey[id]||(state.journey[id]={quiz:{},activity:false,mission:false,tiles:{}})}
function c2Values(t){return Object.fromEntries((t.activity.controls||[]).map(c=>[c.name,Number($('c2-'+c.name)?.value??c.value)]))}
function c2Field(key,label,kind,i){return `<label for="${key}">${c2Esc(label)}</label><div class="answer"><input id="${key}" autocomplete="off" inputmode="${kind==='practice'&&typeof B[modules.find(x=>x.id===state.last).kind][i][0]==='number'?'decimal':'text'}"><button type="button" data-c2-check="${kind}" data-i="${i}">Перевірити</button></div><p id="${key}-fb" aria-live="polite"></p>`}
function c2ActivityHTML(t){const a=t.activity;if(a.type==='range'){const v=Object.fromEntries(a.controls.map(c=>[c.name,c.value]));const d=a.draw(v);return a.controls.map(c=>`<label class="c2-range" for="c2-${c.name}">${c.label}: <output id="c2-${c.name}-value">${c.value}</output><input id="c2-${c.name}" type="range" min="${c.min}" max="${c.max}" value="${c.value}" step="${c.step}" data-c2-range></label>`).join('')+`<div id="c2-picture">${d.html}</div><p id="c2-note">${d.note}</p><p>${a.check.q}</p>${c2Field('c2-model',a.check.label,'model',0)}`}
 if(a.type==='order')return `<p>Натискай картки в потрібному порядку.</p><div class="c2-tokens">${a.tokens.map((x,i)=>`<button type="button" data-c2-token="${i}">${c2Esc(x)}</button>`).join('')}</div><div id="c2-built" class="built" aria-live="polite">Тут з’явиться твоя послідовність.</div><div class="actions"><button data-c2-order>Перевірити порядок</button><button class="secondary" data-c2-undo>Забрати останнє</button><button class="secondary" data-c2-reset>Почати знову</button></div><p id="c2-activity-fb" aria-live="polite"></p>`;
 if(a.type==='paint'){const tiles=c2Rec(state.last).tiles;return `<p>Обери колір і торкайся клітинок. Твій малюнок збережеться на цьому пристрої.</p><div class="actions">${a.colors.map(c=>`<button data-c2-color="${c[1]}" style="border-bottom:6px solid ${c[1]}" class="secondary">${c[0]}</button>`).join('')}</div><div class="c2-canvas">${Array.from({length:12},(_,i)=>`<button data-c2-paint="${i}" aria-label="Клітинка ${i+1}" style="background:${tiles[i]||'#ffffff'}"></button>`).join('')}</div><button data-c2-created>Я завершив / завершила</button><p id="c2-activity-fb" aria-live="polite"></p>`}
 return c2ChoiceHTML(t);
}
function c2ChoiceHTML(t){const a=t.activity,q=a.items[c2Session.step];if(!q)return `<p>✓ Ти дослідив / дослідила всі ${a.items.length} ситуації.</p><button class="secondary" data-c2-reset>Спробувати знову</button><p id="c2-activity-fb" aria-live="polite"></p>`;return `<p class="small">Ситуація ${c2Session.step+1} з ${a.items.length}</p><p class="c2-prompt">${c2Esc(q.label)}</p>${t.speak?`<button class="secondary" data-c2-speak>Послухати англійською</button><p id="c2-speech-fb" aria-live="polite"></p>`:''}<div class="c2-options">${q.options.map((x,i)=>`<button data-c2-pick="${i}">${c2Esc(x)}</button>`).join('')}</div><p id="c2-activity-fb" aria-live="polite"></p>`}
function c2Lesson(m){const t=C2[m.id],r=c2Rec(m.id),bank=B[m.kind],done=(state.done[m.id]||[]).map(String);return `<div class="card c2-lesson" data-topic="${m.id}"><span class="pill">${names[m.s]} · 2 клас</span><h1>${m.title}</h1><p class="c2-goal">${t.goal}</p><section class="c2-block"><h2>${t.heading}</h2>${t.text}<div class="c2-rule">${t.rule}</div><p><b>Спробуй пояснити:</b> ${t.example}</p></section><section class="c2-block"><h2>${t.modelTitle}</h2><p>${t.prompt}</p><div id="c2-activity">${c2ActivityHTML(t)}</div></section><section class="c2-block"><h2>Тренуйся у своєму темпі</h2><p id="c2-count">Виконано ${done.length} із 6 задач. Можна робити перерви й повертатися.</p>${bank.map((q,i)=>`<div class="question"><h3>Задача ${i+1}</h3><p>${c2Esc(q[1])}</p>${c2Field('c2-p'+i,typeof q[0]==='number'?'Відповідь числом':'Відповідь словом або знаком','practice',i)}<p id="c2-done${i}" class="small">${done.includes(String(i))?'✓ Уже виконано':''}</p></div>`).join('')}</section><section class="c2-block"><h2>Перевір, як ти розумієш</h2>${t.quiz.map((q,i)=>`<div class="question"><p>${q.q}</p><div class="c2-options">${q.options.map((o,j)=>`<button data-c2-quiz="${i}" data-a="${j}">${c2Esc(o)}</button>`).join('')}</div><p id="c2-q${i}-fb" aria-live="polite">${r.quiz[i]?'✓ Раніше виконано':''}</p></div>`).join('')}</section><section class="c2-block c2-mission"><h2>Маленька життєва задача</h2><p>${t.mission.text}</p><p>${t.mission.q}</p>${c2Field('c2-mission','Твоя відповідь','mission',0)}${r.mission?'<p>✓ Раніше виконано</p>':''}</section><section class="c2-block"><h2>Спробуй без екрана</h2><p>${t.offline}</p><p class="small">Можна попросити дорослого допомогти прочитати завдання. Тут немає оцінки за швидкість.</p></section><details class="c2-block"><summary>Для дорослих: матеріали до теми</summary><p>${t.source||'Це власні вправи до теми 2-го класу. Звірити зміст можна з типовою програмою початкової школи.'}</p><a href="${C2_PROGRAM}" target="_blank" rel="noopener">Офіційна програма МОН для 1–2 класів ↗</a><p><a href="https://lib.imzo.gov.ua/" target="_blank" rel="noopener">Електронна бібліотека ІМЗО: підручники 2-го класу ↗</a></p></details><div class="c2-nav"><button class="secondary" onclick="home()">На головну</button><button data-c2-next>Наступна тема</button></div></div>`}
openLesson=function(id){const m=modules.find(x=>x.id===id);if(!m)return;state.last=id;persist();hide();$('course').classList.remove('hidden');c2Session={step:0,built:[],color:'#ed775f'};$('side').innerHTML=`<div class="c2-mobile"><label for="c2-topic">Обери тему</label><select id="c2-topic">${modules.map(x=>`<option value="${x.id}" ${id===x.id?'selected':''}>${names[x.s]} · ${x.title}</option>`).join('')}</select></div><div class="c2-desktop">${modules.map(x=>`<button data-c2-open="${x.id}" class="${x.id===id?'c2-current':''}">${names[x.s]}<br>${x.title}</button>`).join('')}</div>`;$('lesson').innerHTML=c2Lesson(m);window.scrollTo(0,0)};
function c2Equal(raw,ans,sensitive=false){if(typeof ans==='number'){const s=raw.trim().replace(',','.').replace(/−/g,'-');return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)&&Math.abs(Number(s)-ans)<0.001}const tidy=s=>String(s).trim().replace(/[’ʼ']/g,"'").replace(/\s+/g,' ');return sensitive?tidy(raw)===tidy(ans):tidy(raw).toLocaleLowerCase('uk-UA')===tidy(ans).toLocaleLowerCase('uk-UA')}
function c2Feedback(key,ok,text){const f=$(key);f.className=ok?'feedback ok':'feedback bad';f.textContent=(ok?'✓ ':'Спробуй ще: ')+text}
function c2Record(id,kind,i,ok){const r=c2Rec(id);if(kind==='practice'){state.attempts++;if(ok){state.correct++;state.done[id]=state.done[id]||[];if(!state.done[id].map(String).includes(String(i)))state.done[id].push(String(i));}else state.errors[id]=(state.errors[id]||0)+1;state.review[id]=Date.now()+(ok?3:1)*86400000;state.history.push({id,ok,v:i,t:Date.now()});if(state.history.length>500)state.history=state.history.slice(-500)}else if(ok){if(kind==='quiz')r.quiz[i]=true;else r[kind]=true}persist()}
document.addEventListener('change',e=>{if(e.target.id==='c2-topic')openLesson(e.target.value)});
document.addEventListener('input',e=>{if(!e.target.hasAttribute('data-c2-range'))return;const t=C2[state.last],d=t.activity.draw(c2Values(t));$(e.target.id+'-value').textContent=e.target.value;$('c2-picture').innerHTML=d.html;$('c2-note').textContent=d.note});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.c2Open){openLesson(b.dataset.c2Open);return}const t=C2[state.last];if(!t||!$('course')||$('course').classList.contains('hidden'))return;const a=t.activity;
 if(b.hasAttribute('data-c2-next')){openLesson(modules[(modules.findIndex(x=>x.id===state.last)+1)%modules.length].id);return}
 if(b.dataset.c2Check){const kind=b.dataset.c2Check,i=Number(b.dataset.i),key=kind==='model'?'c2-model':kind==='mission'?'c2-mission':'c2-p'+i,raw=$(key).value;if(!raw.trim()){c2Feedback(key+'-fb',false,'Введи відповідь, а тоді натисни «Перевірити».');return}const q=kind==='practice'?B[modules.find(x=>x.id===state.last).kind][i]:kind==='mission'?t.mission:a.check,ans=kind==='practice'?q[0]:kind==='model'?q.answer(c2Values(t)):q.ans,ok=c2Equal(raw,ans,(state.last==='u-spell'&&(kind==='mission'||kind==='practice'&&[1,4].includes(i)))||(state.last==='e-hello'&&kind==='practice'&&i===4)||(state.last==='e-sent'&&kind==='practice'&&[4,5].includes(i)));c2Feedback(key+'-fb',ok,kind==='practice'?t.tips[i]:ok?q.why:q.hint);c2Record(state.last,kind==='model'?'activity':kind,i,ok);if(kind==='practice'&&ok){$('c2-done'+i).textContent='✓ Уже виконано';$('c2-count').textContent=`Виконано ${new Set((state.done[state.last]||[]).map(String)).size} із 6 задач.`}return}
 if(b.dataset.c2Quiz!==undefined){const i=Number(b.dataset.c2Quiz),q=t.quiz[i],ok=Number(b.dataset.a)===q.a;c2Feedback('c2-q'+i+'-fb',ok,q.why);c2Record(state.last,'quiz',i,ok);return}
 if(b.dataset.c2Pick!==undefined){const q=a.items[c2Session.step],ok=Number(b.dataset.c2Pick)===q.a;if(ok){c2Session.step++;$('c2-activity').innerHTML=c2ChoiceHTML(t);if(c2Session.step===a.items.length)c2Record(state.last,'activity',0,true)}c2Feedback('c2-activity-fb',ok,q.why);return}
 if(b.dataset.c2Token!==undefined){const i=Number(b.dataset.c2Token);if(c2Session.built.includes(i))return;c2Session.built.push(i);b.disabled=true;$('c2-built').textContent=c2Session.built.map(x=>a.tokens[x]).join(' ').replace(/\s+([.!?,])/g,'$1');return}
 if(b.hasAttribute('data-c2-undo')){const i=c2Session.built.pop();if(i!==undefined)document.querySelector('[data-c2-token="'+i+'"]').disabled=false;$('c2-built').textContent=c2Session.built.map(x=>a.tokens[x]).join(' ').replace(/\s+([.!?,])/g,'$1')||'Тут з’явиться твоя послідовність.';return}
 if(b.hasAttribute('data-c2-order')){const ok=c2Session.built.length===a.answer.length&&c2Session.built.every((x,i)=>x===a.answer[i]);c2Feedback('c2-activity-fb',ok,ok?'Порядок підходить. Поясни, чому саме так.':a.hint);c2Record(state.last,'activity',0,ok);return}
 if(b.hasAttribute('data-c2-reset')){c2Session.step=0;c2Session.built=[];$('c2-activity').innerHTML=c2ActivityHTML(t);return}
 if(b.dataset.c2Color){c2Session.color=b.dataset.c2Color;return}
 if(b.dataset.c2Paint!==undefined){const r=c2Rec(state.last);r.tiles[b.dataset.c2Paint]=c2Session.color;b.style.background=c2Session.color;persist();return}
 if(b.hasAttribute('data-c2-created')){const painted=Object.keys(c2Rec(state.last).tiles).length;if(!painted){c2Feedback('c2-activity-fb',false,'Обери колір і зафарбуй хоча б одну клітинку.');return}c2Feedback('c2-activity-fb',true,'Твій задум збережено. У творчості може бути багато вдалих рішень.');c2Record(state.last,'activity',0,true);return}
 if(b.hasAttribute('data-c2-speak')){const q=a.items[c2Session.step];if(!('speechSynthesis'in window)){$('c2-speech-fb').textContent='Озвучення тут недоступне. Прочитай фразу з дорослим.';return}const voice=speechSynthesis.getVoices().find(v=>/^en[-_]/i.test(v.lang));if(!voice){$('c2-speech-fb').textContent='Англійський голос недоступний. Прочитай фразу з дорослим.';return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.label);u.voice=voice;u.lang='en-GB';u.rate=0.8;u.onerror=()=>{$('c2-speech-fb').textContent='Не вдалося озвучити. Можна прочитати з дорослим.'};speechSynthesis.speak(u)}
});
