/* Linear equations: additive state only; existing variant indices stay intact. */
const EQ_EXTRA = [
 {text:'Розв’яжи: x/3 + 2 = 5.',ans:9,why:'Відніми 2: x/3=3. Помнож обидві частини на 3: x=9.'},
 {text:'Розв’яжи: 0,5x − 1 = 2.',ans:6,why:'Додай 1: 0,5x=3. Поділи на 0,5: x=6. Ділення на половину подвоює число.'}
];
const EQ_WHY = ['4x=31−7=24, тому x=6. Перевірка: 4·6+7=31.', '5x=20+10=30, тому x=6. Віднімання 10 компенсуємо додаванням.', '−3x=6−18=−12, тому x=4. Діли на −3, а не на 3.', 'x=−35/7=−5. Від’ємне число, поділене на додатне, дає від’ємне.', 'x+3=14/2=7, тому x=4. При розкритті дужок множник 2 стосується обох доданків.', 'Відніми x та 5 від обох частин: 2x=12, тому x=6.'];
const EQ_QUIZ = [
 {q:'Що означає, що 4 — корінь рівняння?',o:['Після підстановки x=4 рівність правильна','У рівнянні є цифра 4','Обидві частини дорівнюють 4'],a:0,why:['Так: корінь перетворює рівняння на правильну числову рівність.','Наявність цифри не визначає корінь. Потрібно підставити 4 замість x.','Частини мають бути рівними між собою, але не обов’язково дорівнювати 4.']},
 {q:'Який крок рівносильний 3x+6=15?',o:['3x=15','x+2=5','x+6=5'],a:1,why:['Віднявши 6 зліва, потрібно відняти 6 і справа: 3x=9.','Усі доданки обох частин поділено на 3.','На 3 треба ділити й доданок 6: отримаємо x+2=5.']},
 {q:'Що можна сказати про 2(x+1)=2x+2?',o:['Єдиний корінь 0','Коренів немає','Будь-яке число є коренем'],a:2,why:['Нуль підходить, але підходить і будь-яке інше число.','Після розкриття дужок частини однакові — суперечності немає.','Після віднімання 2x маємо 2=2. Рівність правильна для будь-якого x.']},
 {q:'Скільки коренів має 2x+1=2x+4?',o:['Жодного','Один: 3','Безліч'],a:0,why:['Після віднімання 2x маємо хибну рівність 1=4.','Члени з x взаємно знищуються: 0x=3, а не x=3.','Безліч коренів було б при правильній рівності, наприклад 1=1.']},
 {q:'Чому не можна ділити обидві частини на 0?',o:['Можна, якщо справа 0','Ділення на 0 не визначене','Тільки тому, що x невідомий'],a:1,why:['Навіть 0/0 не визначене. Такий крок не є допустимим.','Саме так. Множення на 0 теж не є рівносильним кроком: воно втрачає інформацію про корені.','Причина не в невідомому: ділення на 0 не визначене і для чисел.']}
];
function equationState(){return state.equationLearning||(state.equationLearning={practice:{},quiz:{},stem:{}})}
function equationTasks(){return practiceBanks['alg-equation'].map((q,i)=>({...q,why:EQ_WHY[i]})).concat(EQ_EXTRA)}
function equationField(id,label,action){return `<label for="${id}">${label}</label><div class="answer-row"><input id="${id}" type="text" inputmode="decimal" autocomplete="off"><button type="button" class="secondary minus-btn" onclick="insertMinus(this)" aria-label="Додати знак мінус">−</button><button type="button" onclick="${action}">Перевірити</button></div><p id="${id}Fb" aria-live="polite"></p>`}
function equationLesson(){
 const r=equationState();
 return `<section class="card lesson active"><div class="toc-tag">Алгебра · 7 клас</div><h1>Лінійні рівняння</h1>
 <div class="textbook-real"><h2>1. Рівність із невідомим</h2><p><b>Рівняння</b> — рівність, що містить невідоме. <b>Корінь</b> — значення невідомого, за якого рівність правильна. Розв’язати рівняння означає знайти всі корені або встановити, що їх немає.</p><p>Лінійне рівняння з однією змінною має вигляд <b>ax=b</b>, де a і b — відомі числа. Наприклад, 3x+5=20 зводиться до 3x=15. Якщо a≠0, є єдиний корінь x=b/a. Якщо a=0, то при b=0 підходить будь-яке число, а при b≠0 коренів немає.</p><div class="coord-fact"><b>Рівносильні рівняння мають однакові корені.</b><ul><li>До обох частин можна додати або від обох частин відняти те саме число чи той самий вираз, визначений для всіх розглянутих x.</li><li>Обидві частини можна помножити або поділити на те саме <b>ненульове</b> число.</li></ul></div><p>«Перенести доданок зі зміною знака» — скорочений запис віднімання цього доданка від обох частин. Діли <b>всю частину</b>, а не лише член з x.</p></div>
 <h2>2. Терези: збережи рівновагу</h2><p>Три однакові коробки та гиря 5 кг урівноважують 20 кг. Невідома маса коробки — x кг. Спершу прибери 5 кг з обох шальок, потім поділи обидві маси на 3. Кнопка дії лише зліва показує, чому рівність порушується.</p><div class="coord-stage"><div id="eqBalance">${equationBalanceHTML(0)}</div><div class="actions"><button type="button" onclick="equationBalance('subtract')">−5 з обох частин</button><button type="button" onclick="equationBalance('divide')">÷3 обох частин</button><button type="button" class="secondary" onclick="equationBalance('one')">−5 лише зліва</button><button type="button" class="ghost" onclick="equationBalance('reset')">Почати модель знову</button></div><p id="eqBalanceFb" aria-live="polite">Початкове рівняння: 3x+5=20.</p></div>
 <h2>3. Як розв’язувати</h2><ol><li>Розкрий дужки; за потреби позбудься дробів множенням усіх доданків на спільний знаменник.</li><li>Збери члени з x в одній частині, числа — в іншій.</li><li>Зведи подібні доданки й поділи на ненульовий коефіцієнт.</li><li>Підстав корінь у початкове рівняння.</li></ol><div class="worked-example"><b>Дужки та невідоме з обох боків:</b> 2(x−3)=x+4 → 2x−6=x+4 → x−6=4 → x=10. Перевірка: 2·(10−3)=10+4=14.</div><div class="worked-example"><b>Від’ємний коефіцієнт:</b> 5−2x=13 → −2x=8 → x=−4. Перевірка: 5−2·(−4)=13.</div><div class="worked-example"><b>Дроби:</b> x/2+1=4 → x+2=8 → x=6. На 2 множимо кожен доданок обох частин.</div>
 <h2>4. Практика</h2><p>Вводь лише число; десятковий роздільник — кома або крапка. Перші шість задач зберігають попередній прогрес курсу.</p>${equationTasks().map((q,i)=>`<div class="q"><h3>Задача ${i+1}</h3><p>${q.text}</p>${equationField('eqP'+i,'Значення x',`equationPractice(${i})`)}<span id="eqDone${i}">${r.practice[i]||((state.completedVariants['alg-equation']||[]).map(String).includes(String(i)))?'✓ Уже розв’язано':''}</span></div>`).join('')}
 <h2>5. Тест на розуміння</h2>${EQ_QUIZ.map((q,i)=>`<div class="q"><p><b>${q.q}</b></p><div class="kt-options">${q.o.map((o,j)=>`<button type="button" onclick="equationQuiz(${i},${j})">${o}</button>`).join('')}</div><p id="eqQ${i}" aria-live="polite">${r.quiz[i]===true?'✓ Правильну відповідь уже знайдено':''}</p></div>`).join('')}
 <h2>6. STEM: наздогнати робота</h2><p>На прямій доріжці робот А перебуває на позначці 6 м та рухається зі сталою швидкістю 2 м/с. Одночасно робот Б стартує з позначки 0 м у тому самому напрямку зі швидкістю 3 м/с. Коли Б наздожене А? Доріжка достатньо довга, швидкості сталі.</p><p>Через t секунд координати: <b>s<sub>A</sub>=6+2t</b>, <b>s<sub>Б</sub>=3t</b>. У момент зустрічі координати рівні: <b>6+2t=3t</b>. Усі відстані — у метрах, час — у секундах.</p><div class="q">${equationField('eqST','Час до зустрічі, с','equationStem(0)')}<div id="eqStemNext" ${r.stem[0]?'':'hidden'}>${equationField('eqSS','Координата зустрічі, м','equationStem(1)')}</div><p>Поясни собі: чому 6 м — початковий відрив, а не шлях робота А? Чому після розв’язання потрібно перевірити, що t≥0?</p></div>
 <h2>7. Урок ВШО</h2><p><a href="https://lms.e-school.net.ua/courses/course-v1%3AUIED%2BAlgebra-7th-grade%2B2020/courseware/a78ce845878841b7b9b1da96877e814d/fa62fff846ac496e84868c1de019046c/" target="_blank" rel="noopener noreferrer">Урок 49. Лінійне рівняння з однією змінною — офіційна ВШО ↗</a>. Для виконання завдань на платформі потрібен вхід.</p><div class="lesson-nav"><button type="button" class="secondary" onclick="showHome()">На головну</button><button type="button" onclick="nextLesson('alg-equation')">Наступна тема</button></div></section>`;
}
function equationBalanceHTML(step){
 const labels=[['3x + 5','20'],['3x','15'],['x','5'],['3x','20']][step];
 return `<svg viewBox="0 0 400 220" role="img" aria-label="Терези: ${labels[0]} ${step===3?'не дорівнює':'дорівнює'} ${labels[1]}" style="width:100%;max-width:480px"><path d="M170 205 L200 100 L230 205 Z" fill="#dbe4f5"/><g transform="rotate(${step===3?10:0} 200 85)"><path d="M65 85 H335 M80 85 V145 M320 85 V145" fill="none" stroke="#3156d3" stroke-width="6"/><path d="M25 145 Q80 210 135 145 Z M265 145 Q320 210 375 145 Z" fill="#b8daf3"/><text x="80" y="130" text-anchor="middle" font-size="23">${labels[0]}</text><text x="320" y="130" text-anchor="middle" font-size="23">${labels[1]}</text></g></svg><p class="formula" data-step="${step}">${labels[0]} ${step===3?'≠':'='} ${labels[1]}</p>`;
}
function equationBalance(action){
 const box=$('eqBalance'),step=Number(box.querySelector('[data-step]').dataset.step);let next=step,msg='';
 if(action==='reset'){next=0;msg='Початкове рівняння відновлено. Прогрес завдань збережено.'}
 else if(action==='one'){next=3;msg='За x=5 зліва тепер 15 кг, справа 20 кг. Праворуч важче! Це не рівносильне перетворення. Почни модель знову.'}
 else if(action==='subtract'&&step===0){next=1;msg='3x+5−5=20−5 → 3x=15. Рівновага збережена.'}
 else if(action==='divide'&&step===1){next=2;msg='3x/3=15/3 → x=5 кг. Перевірка: 3·5+5=20 кг.'}
 else if(action==='divide'&&step===0){msg='Ділити на 3 можна, але отримаємо x+5/3=20/3. У цій моделі спершу прибери 5 з обох частин.'}
 else {msg=step===2?'Корінь уже знайдено: x=5. Можеш почати модель знову.':'Почни модель знову, щоб виконати ці кроки послідовно.'}
 box.innerHTML=equationBalanceHTML(next);$('eqBalanceFb').textContent=msg;
}
function equationNumber(id){const raw=$(id).value.trim().replace(/−/g,'-').replace(',','.');return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(raw)&&Number.isFinite(Number(raw))?Number(raw):null}
function equationPractice(i){
 const q=equationTasks()[i],v=equationNumber('eqP'+i),fb=$('eqP'+i+'Fb');if(v===null){fb.textContent='Введи число, наприклад −5 або 0,5. Порожня відповідь не зараховується.';return}
 const ok=Math.abs(v-q.ans)<1e-9,r=equationState();fb.textContent=(ok?'✓ Правильно. ':'↩ Перевір перетворення. ')+q.why;
 if(ok){r.practice[i]=true;$('eqDone'+i).textContent='✓ Розв’язано'}
 state.attempts++;if(ok)state.correct++;
 state.history.push({id:'alg-equation',ok,t:Date.now()});
 if(i<6){state.completedVariants['alg-equation']=state.completedVariants['alg-equation']||[];const done=state.completedVariants['alg-equation'];if(ok&&!done.map(String).includes(String(i)))done.push(String(i));state.skills['Рівняння']=Math.max(state.skills['Рівняння']||0,Math.round(new Set(done.map(String)).size/6*100));}
 if(!ok)state.errors['Рівняння']=(state.errors['Рівняння']||0)+1;
 persistState();
}
function equationQuiz(i,j){const q=EQ_QUIZ[i],ok=j===q.a;$('eqQ'+i).textContent=(ok?'✓ ':'↩ ')+q.why[j];equationState().quiz[i]=ok;persistState()}
function equationStem(i){const id=i===0?'eqST':'eqSS',v=equationNumber(id);if(v===null){$(id+'Fb').textContent='Введи числову відповідь у зазначених одиницях.';return}const ok=Math.abs(v-(i===0?6:18))<1e-9;$(id+'Fb').textContent=(ok?'✓ ':'↩ ')+(i===0?'6+2t=3t → 6=t. Відрив 6 м скорочується зі швидкістю 3−2=1 м/с.':'sБ=3·6=18 м; sА=6+2·6=18 м. Координати збіглися; робот А проїхав лише 12 м.');if(ok){equationState().stem[i]=true;if(i===0)$('eqStemNext').hidden=false;persistState()}}
