const fs=require('fs'),path=require('path'),http=require('http'),vm=require('vm'),assert=require('assert');const {chromium}=require(process.env.STEM7_PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(__dirname,'..');for(const file of fs.readdirSync(path.join(root,'lessons')).filter(x=>x.endsWith('.js')))new vm.Script(fs.readFileSync(path.join(root,'lessons',file),'utf8'),{filename:file});for(const [,code]of fs.readFileSync(path.join(root,'index.html'),'utf8').matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(code);new vm.Script(fs.readFileSync(path.join(root,'sw.js'),'utf8'));
(async()=>{const server=http.createServer((req,res)=>{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');const browser=await chromium.launch({channel:process.env.STEM7_BROWSER_CHANNEL||'msedge',headless:true});try{const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>typeof RB==='object'&&Object.keys(RB).length===75);assert.equal(await page.locator('.subject-learn').count(),5);assert.equal(await page.locator('#yearMap .mapcol').count(),5);assert.equal(await page.evaluate(()=>lessons.length),76);
 await page.evaluate(()=>{state.testSentinel='preserved';state.skills['Кути']=85;state.completedVariants['alg-expr']=['0'];state.angleLearning={step:4,testScore:3};state.last='alg-expr';persistState()});const legacy=await page.evaluate(()=>({done:state.completedVariants['alg-expr'],angle:state.angleLearning,skills:state.skills['Кути'],keys:[KEY,BACKUP_KEY]}));await page.locator('#continueBtn').click();assert.equal(await page.locator('[data-rebuilt]').getAttribute('data-rebuilt'),'alg-expr');
 async function answer(key,value){const f=page.locator('#'+key);if(await f.evaluate(el=>el.tagName)==='SELECT')await f.selectOption(String(value));else await f.fill(String(value));await f.locator('..').locator('[data-rb-check]').click()}
 async function feedback(key,ok){const value=await page.locator('#'+key+'-fb').innerText();assert(value.startsWith(ok?'✓':'↩')||(!ok&&value.startsWith('Введи')),key+' '+value)}
 let practice=0,quiz=0,missions=0,activities=0;const ids=await page.evaluate(()=>lessons.filter(l=>['bio','chem'].includes(l.s)).map(l=>l.id));assert.equal(ids.length,25);
 for(const id of ids){await page.locator('#mobileLessonSelect').selectOption(id);const data=await page.evaluate(id=>({a:RB[id].activity,controls:RB[id].controls,bank:practiceBanks[id],quiz:RB[id].quiz,steps:RB[id].mission.steps}),id);assert.equal(data.bank.length,6);assert.equal(data.quiz.length,2);assert.equal(data.steps.length,2);
  if(data.a){for(const q of data.a.stages){await page.locator('[data-ns-pick="'+((q.a+1)%q.options.length)+'"]').click();assert((await page.locator('#ns-feedback').innerText()).startsWith('↩'));await page.locator('[data-ns-pick="'+q.a+'"]').click();assert((await page.locator('#ns-feedback').innerText()).startsWith('✓'))}assert(await page.evaluate(()=>rbState(state.last).exploration));await page.locator('[data-ns-restart]').click();assert.equal(await page.evaluate(()=>nsPosition),0)}else{await answer('rb-explore','');await feedback('rb-explore',false);for(const c of data.controls)for(const v of [c.min,c.max]){await page.locator('#rb-'+c.name).fill(String(v));assert(!(await page.locator('#rb-model').innerHTML()).match(/NaN|Infinity|undefined/));const ans=await page.evaluate(()=>RB[state.last].check.answer(rbRead(RB[state.last])));await answer('rb-explore',ans+10000);await feedback('rb-explore',false);await answer('rb-explore',ans);await feedback('rb-explore',true)}}activities++;
  for(const [i,q]of data.bank.entries()){await answer('rb-p'+i,q.options?'': '');await feedback('rb-p'+i,false);const wrong=q.options?q.options.find(o=>o!==q.ans):Number(q.ans)+10000;await answer('rb-p'+i,wrong);await feedback('rb-p'+i,false);await answer('rb-p'+i,q.ans);await feedback('rb-p'+i,true);practice++}const n=await page.evaluate(()=>state.completedVariants[state.last].length);await answer('rb-p0',data.bank[0].ans);assert.equal(await page.evaluate(()=>state.completedVariants[state.last].length),n);assert.equal(await page.evaluate(()=>state.skills[lessons.find(l=>l.id===state.last).skill]),100);
  for(const [i,q]of data.quiz.entries()){await page.locator('[data-rb-quiz="'+i+'"]').click();await feedback('rb-q'+i,false);for(const a of q.correct)await page.locator('input[name="rb-q'+i+'"][value="'+a+'"]').check();await page.locator('[data-rb-quiz="'+i+'"]').click();await feedback('rb-q'+i,true);quiz++}
  assert(!await page.locator('#rb-m1-stage').isVisible());for(const [i,q]of data.steps.entries()){await answer('rb-m'+i,q.ans+10000);await feedback('rb-m'+i,false);await answer('rb-m'+i,q.ans);await feedback('rb-m'+i,true);missions++}console.log(id+' passed');
 }
 // Independent content and case checks, beyond wiring the authored answers.
 await page.locator('#mobileLessonSelect').selectOption('chem-elements');await answer('rb-p0','NA');await feedback('rb-p0',false);await answer('rb-p0','na');await feedback('rb-p0',false);await answer('rb-p0','Na');await feedback('rb-p0',true);await answer('rb-p3',2);await feedback('rb-p3',true);await answer('rb-p4',1);await feedback('rb-p4',true);
 await page.locator('#mobileLessonSelect').selectOption('chem-formula');await answer('rb-p0',6);await feedback('rb-p0',true);await page.locator('#mobileLessonSelect').selectOption('bio-invertebrates');await answer('rb-p0',6);await feedback('rb-p0',true);await answer('rb-p1',8);await feedback('rb-p1',true);
 for(const width of [360,390,768,1280]){await page.setViewportSize({width,height:900});for(const id of ids){await page.evaluate(id=>directOpenLesson(id),id);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),id+' overflow '+width)}await page.screenshot({path:path.join(require('os').tmpdir(),'natural-'+width+'.png')})}
 await page.setViewportSize({width:390,height:844});for(const subject of ['bio','chem']){await page.evaluate(()=>showHome());await page.locator('[data-subject="'+subject+'"]').click();assert.equal(await page.evaluate(()=>lessons.find(l=>l.id===state.last).s),subject)}
 await page.getByRole('button',{name:'Маршрут',exact:true}).click();assert((await page.locator('#yearPathView').innerText()).includes('Біологія'));await page.getByRole('button',{name:'Батьківський режим',exact:true}).click();assert((await page.locator('#mastery').innerText()).includes('Хімічні формули'));
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;await caches.open('class2-v8');await caches.open('stem7-pwa-v23');for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister()});await page.reload();await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(async()=>!(await caches.keys()).includes('stem7-pwa-v23'));assert((await page.evaluate(()=>caches.keys())).includes('class2-v8'));await context.setOffline(true);await page.reload();await page.locator('#continueBtn').click();for(const id of ids)await page.locator('#mobileLessonSelect').selectOption(id);assert.deepEqual(await page.evaluate(()=>({done:state.completedVariants['alg-expr'],angle:state.angleLearning,skills:state.skills['Кути'],keys:[KEY,BACKUP_KEY]})),legacy);assert.equal(await page.evaluate(()=>state.testSentinel),'preserved');assert.deepEqual(errors,[]);console.log(JSON.stringify({topics:ids.length,practice,quiz,missions,activities,viewports:[360,390,768,1280],offline:true,oldProgressPreserved:true,errors}));
 }finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
