/* Adds two subjects without replacing existing lesson IDs or stored progress. */
const NS_BIO_PROGRAM='https://mon.gov.ua/static-objects/mon/sites/1/zagalna%20serednya/Navchalni.prohramy/2023/Model.navch.prohr.5-9.klas/Pryrodnycha.osvitnya.haluz.2023/04.12.2023/Biologiya.7-9.klas.Samoylov.ta.in-04.12.2023.pdf';
const NS_CHEM_PROGRAM='https://mon.gov.ua/storage/app/media/zagalna%20serednya/Navchalni.prohramy/2023/Model.navch.prohr.5-9.klas/Pryrodnycha.osvitnya.haluz.2023/Khimiya.7-9.klas.Hryhorovych.29.12.2023.pdf';
subjectNames.bio='Біологія';subjectNames.chem='Хімія';
function nsP(text,ans,hint,options){return {text,ans,error:hint,hint,explain:hint,options}}
function nsChoice(q,options,a,why){return {q,options,a,why}}
function nsActivity(svg,...stages){return {svg,stages}}
function nsAdd(s,id,title,t,bank){bank.forEach((q,i)=>{if(s==='chem'&&typeof q.ans==='string'&&/^[A-Za-z]+$/.test(q.ans))q.caseSensitive=true;if(q.options){const n=(id.length+i)%q.options.length;q.options=q.options.slice(n).concat(q.options.slice(0,n))}});t.quiz.forEach((q,i)=>{const n=(id.length+i)%q.options.length;q.options=q.options.slice(n).concat(q.options.slice(0,n));q.correct=q.correct.map(a=>(a-n+q.options.length)%q.options.length)});const l={id,s,title,skill:title,theory:t.rule,q:bank[0]};lessons.push(l);practiceBanks[id]=bank;rbTopic(id,{controls:[],sourceTitle:'Офіційна програма та додаткове навчання',video:s==='bio'?NS_BIO_PROGRAM:NS_CHEM_PROGRAM,videoLabel:s==='bio'?'МОН: модельна програма біології 7–9 класів (Самойлов, Тагліна, Утєвська).':'МОН: модельна програма хімії 7–9 класів (Григорович).',resourceNote:'Посилання веде до повної модельної програми. Наші тематичні заняття доповнюють шкільний курс; послідовність у вашому підручнику може відрізнятися. Зовнішній PDF потребує інтернету, а наші вправи доступні офлайн після завантаження.',...t});if(t.activity)t.activity.stages.forEach((q,i)=>{const n=(id.length+i)%q.options.length;q.options=q.options.slice(n).concat(q.options.slice(0,n));q.a=(q.a-n+q.options.length)%q.options.length})}
function nsCircles(n,x,y,color,label){return Array.from({length:n},(_,i)=>`<circle cx="${x+(i%8)*36}" cy="${y+Math.floor(i/8)*36}" r="13" fill="${color}"/>`+(label?rbText(x+(i%8)*36,y+Math.floor(i/8)*36+5,label,'#fff'):'')).join('')}
function nsChain(labels){return rbSvg(labels.map((t,i)=>rbRect(10+i*118,95,105,65,t)+ (i<labels.length-1?rbText(120+i*118,133,'→'):'')).join(''))}
function nsArrange(){const order=['research','cell','ecosystem','organs','photosynthesis','flower','seed','algae','fungi','animals','invertebrates','vertebrates','unicellular','microbes'].map(x=>'bio-'+x).concat(['lab','matter','atom','elements','formula','simple','mixtures','separation','fraction','changes','reaction'].map(x=>'chem-'+x));const added=order.map(id=>lessons.find(l=>l.id===id));for(let i=lessons.length-1;i>=0;i--)if(['bio','chem'].includes(lessons[i].s))lessons.splice(i,1);lessons.push(...added);for(const s of ['bio','chem'])if(!YEAR_PHASES.some(p=>p.ids.includes(added.find(l=>l.s===s).id)))YEAR_PHASES.push({name:subjectNames[s]+' · дослідження й застосування',desc:'Окремі тематичні заняття з моделями, практикою та STEM-задачами.',ids:added.filter(l=>l.s===s).map(l=>l.id)});render()}
let nsPosition=0;
function nsActivityHTML(t){const a=t.activity,q=a.stages[nsPosition];return `<div class="rb-model">${a.svg}</div>${q?`<p class="rb-lead">${s7Esc(q.q)}</p><div class="actions">${q.options.map((o,i)=>`<button class="ghost" data-ns-pick="${i}" data-ns-id="${state.last}">${s7Esc(o)}</button>`).join('')}</div><p class="small">Крок ${nsPosition+1} з ${a.stages.length}</p>`:'<p>✓ Усі ситуації розібрано. Поясни один із висновків своїми словами.</p><button class="secondary" data-ns-restart>Дослідити знову</button>'}<p id="ns-feedback" aria-live="polite"></p>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-ns-pick],[data-ns-restart]');if(!b)return;const t=RB[state.last];if(b.hasAttribute('data-ns-restart')){nsPosition=0;document.getElementById('ns-activity').innerHTML=nsActivityHTML(t);return}const q=t.activity.stages[nsPosition],ok=Number(b.dataset.nsPick)===q.a;if(ok){nsPosition++;document.getElementById('ns-activity').innerHTML=nsActivityHTML(t);if(nsPosition===t.activity.stages.length){rbState(state.last).exploration=true;persistState()}}const f=document.getElementById('ns-feedback');f.className=ok?'rb-ok':'rb-bad';f.textContent=(ok?'✓ ':'↩ ')+q.why});
